### ISSUE TITLE
Testing links is broken

### ISSUE THREAD

**Issue by adetheprince** [BigHeartC/IPTV_plus#1]
Nice work dear

The site you show on the example is not working
Is it possible to show us example of this site http://tv.byr.cn/mobile/index.html?cdn=bupt
Thanks.

**Comment by BigHeartC** [comment]
this site is inaccessible unless you connect the net of my college, you could set a video url you want in [this line](https://github.com/BigHeartC/IPTV_plus/blob/master/app/src/main/java/com/bigheart/byrtv/ui/view/activity/TvLiveActivity.java#L381).

**Comment by kentakiz** [comment]
how can i add a m3u file in this app,thnx
